# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FMDB使用' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FMDB使用
  pod 'FMDB'
 
  target 'FMDB使用Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FMDB使用UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
